spring:
  datasource:
    url: url
    username: name
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comment: true
  devtools: 
   livereload: 
    enable: true
  freemarker:
   cache: false

api:
  riot:
    url_asia: https://asia.api.riotgames.com
    url_kr: https://kr.api.riotgames.com
    key_tft: key
    key_lol: key
  
  
server:
  port: 8080